%  Function File: bootknife
%
%  Bootknife sampling  
%
%  bootstat = bootknife(nboot,bootfun,d)
%  bootstat = bootknife(nboot,bootfun,d1,...,dN)
%
%  bootstat = bootknife(nboot,bootfun,d,...) draws nboot bootknife data
%  resamples and returns the statistic computed by bootfun in bootstat.
%  Bootknife sampling involves creating leave-one-out jackknife samples
%  of size n - 1 and then drawing bootstrap samples of size n with
%  replacement from the jacknife samples [1]. Unlike for the bootstrap, 
%  the variance of bootstat generated by bootknife sampling provides an 
%  unbiased estimate of the sampling variance for small samples. bootfun 
%  is a function handle (e.g. specified with @), or a string indicating 
%  the function name. The third input argument is data (column vector or 
%  a matrix), that is used to create inputs for bootfun. The resampling 
%  method used is balanced resampling [2].
%
%  bootstat = bootknife(nboot,bootfun,d1,...,dN) is as above except that 
%  the third and subsequent numeric input arguments are data vectors 
%  that are used to create inputs for bootfun. 
%
%  Bibliography:
%  [1] Hesterberg T.C. (2004) Unbiasing the Bootstrap—Bootknife Sampling 
%        vs. Smoothing; Proceedings of the Section on Statistics & the 
%        Environment. Alexandria, VA: American Statistical Association.
%  [2] Davison et al. (1986) Efficient Bootstrap Simulation.
%        Biometrika, 73: 555-66
%
%  bootknife v1.0.0.0 (27/02/2022)
%  Author: Andrew Charles Penn
%  https://www.researchgate.net/profile/Andrew_Penn/
%
%
%  Copyright 2019 Andrew Charles Penn
%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <http://www.gnu.org/licenses/>.


function T = bootknife (nboot, bootfun, varargin)
  
  % Determine properies of data
  x = varargin;
  nvar = numel(x);
  sz = size(x{1});
  n = sz(1);
  if sz(2) > 1
    matflag = 1;
  else
    matflag = 0;
  end 
  
  % Initialize
  w = ones(n, 1);
  B = nboot(1);
  N = n * B;
  T = zeros(1, B);
  X = cell(1, nvar);
  idx = zeros(n, 1);
  c = w * B;

  % Perform balanced (or almost balanced) bootknife resampling
  % Octave or Matlab serial/vectorized computing
  for h = 1:B
    r = h - fix((h-1)/n) * n;
    for i = 1:n
      d = c;   
      d(r) = 0;
      k = sum(i>n)+1; 
      j = sum((rand(1) >= cumsum(d./sum(d)))) + 1;
      idx(i, 1) = j;
      c(j) = c(j) - 1;
    end
    for v = 1:nvar
      X{v}(:,h) = x{v}(idx);
    end
    % Function evaluations performed in a Matlab loop
    if matflag || (nvar > 1)
      for v = 1:nvar
        X{v} = x{v}(idx);
      end
      T(h) = feval(bootfun,X{:});
    else
      for v = 1:nvar
        X{v}(:,h) = x{v}(idx);
      end
    end
  end
  % Vectorized function evaluations on bootstrap data samples
  if ~matflag && (nvar == 1)
    T = feval(bootfun,X{:});
  end

end
